from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^group/is_in_group/$', 'groups.views.is_in_group'),
    (r'^group/join_group/$', 'groups.views.join_group'),
    (r'^group/leave_group/$', 'groups.views.leave_group'),
    (r'^get_groups_view_json/$', 'groups.views.get_groups_view_json'),
    (r'^get_discussions_view_json/(?P<group_slug>.*)$', 'groups.views.get_discussions_view_json'),
    (r'^group/(?P<group_slug>.*)/$', 'groups.views.group_home'),
    (r'^discussions_list/(?P<group_slug>.*)/$', 'discussions.views.discussions_list'),
    (r'^discussion-delete/(?P<discussion_pk>\w+)/$', 'discussions.views.delete_discussion'),
    (r'^stories_list/(?P<discussion_slug>.*)/$', 'discussions.views.stories_list'),
    (r'^story-delete/(?P<story_pk>\w+)/$', 'discussions.views.delete_story'),
    (r'^group-delete/(?P<group_pk>.*)/$', 'groups.views.delete_group'),
    (r'^member-delete/(?P<group_pk>\w+)/(?P<member_pk>\w+)/$', 'groups.views.delete_member'),
    (r'^member-promote/(?P<group_pk>\w+)/(?P<member_pk>\w+)/$', 'groups.views.promote_member'),
    (r'^member-demote/(?P<group_pk>\w+)/(?P<member_pk>\w+)/$', 'groups.views.demote_member'),
    (r'^users/(?P<user_name>.*)/$', 'groups.views.user_home'),
    (r'^user-profile/$', 'groups.views.edit_user_profile'),
    (r'^groups_list/$', 'groups.views.groups_list'),
    (r'^members_list/(?P<group_slug>.*)/$', 'groups.views.members_list'),
    #(r'^login/$', 'groups.views.login'),
    (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'admin/login.html'}),
    (r'^$', 'groups.views.home'),
)
