from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^groups/add_group/$', 'groups.views.add_group'),
    (r'^groups/set_mission_statement/(?P<group_pk>.*)$', 'groups.views.set_mission_statement'),
    (r'^group/is_in_group/$', 'groups.views.is_in_group'),
    (r'^group/join_group/$', 'groups.views.join_group'),
    (r'^group/leave_group/$', 'groups.views.leave_group'),
    (r'^get_groups_view_json/$', 'groups.views.get_groups_view_json'),
    (r'^get_discussions_view_json/(?P<group_slug>.*)$', 'groups.views.get_discussions_view_json'),
    (r'^group/(?P<group_slug>.*)/settings/set_new_group_manager/(?P<member_pk>\w+)/$', 'groups.views.set_new_group_manager'),
    (r'^group/(?P<group_slug>.*)/settings/$', 'groups.views.group_settings'),
    (r'^group/(?P<group_slug>.*)/$', 'groups.views.group_home'),
    (r'^discussions_list/(?P<group_slug>.*)/$', 'discussions.views.discussions_list'),
    (r'^discussion-delete/(?P<discussion_pk>\w+)/$', 'discussions.views.delete_discussion'),
    (r'^stories_list/(?P<discussion_slug>.*)/$', 'discussions.views.stories_list'),
    (r'^group-delete/(?P<group_pk>.*)/$', 'groups.views.delete_group'),
    (r'^member-delete/(?P<group_pk>\w+)/(?P<member_pk>\w+)/$', 'groups.views.delete_member'),
    (r'^member-promote/(?P<group_pk>\w+)/(?P<member_pk>\w+)/$', 'groups.views.promote_member'),
    (r'^member-demote/(?P<group_pk>\w+)/(?P<member_pk>\w+)/$', 'groups.views.demote_member'),
    (r'^users/(?P<user_name>.*)/$', 'groups.views.user_home'),
    (r'^user-profile/$', 'groups.views.edit_user_profile'),
    (r'^user-profile/delete_picture/$', 'groups.views.delete_picture'),
    (r'^groups_list/$', 'groups.views.groups_list'),
    (r'^members_list/(?P<group_slug>.*)/$', 'groups.views.members_list'),
    (r'^approve/(?P<approve_key>.+)$', 'groups.views.approve_user'),
    #(r'^login/$', 'groups.views.login'),
    (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'admin/login.html'}),
    (r'^groups/$', 'groups.views.groups'),
    (r'^$', 'groups.views.home'),

    (r'^im_api/get_user_groups/(?P<user_im_address>.*)/$', 'groups.views.get_user_groups_by_im'),
    (r'^im_api/get_group_members/(?P<group_pk>.*)/', 'groups.views.get_group_members'),

)
